### ISSUE TITLE
address-book-app does not have a maintainer

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/address-book-app#1]
No one is currently maintaining this app. If you would like to become the maintainer, please reply to this issue or get a hold of us via another method.

The app maintainers will be responsible for coordinating the following (doing it yourself is still coordinating, if you prefer that):

* Triaging bugs
* Fixing bugs
* Vetting and implementing enhancement requests
* Corresponding with the UBports project regarding the app's progress
* Requesting bounties be posted for the app
* Keeping a little booklet with everyone's contact information in it

**Comment by lkristensen** [comment]
Since this app uses the same back end as the calendar app, it might make sense if I take ownership of this one as well.

**Comment by NeoTheThird** [comment]
Yay!
