### ISSUE TITLE
on dual sim devices only one number is gives as "my phone number"

### ISSUE THREAD

**Issue by Danfro** [ubports/address-book-app#106]
E5, dev channel

When opening the settings page, after 1 or 2 seconds a field containing information on "my phone number" appears. This field does display only the number of my second sim card. With dual sim devices it should show:

a) the "primary" number set for calls/sms/mobile data [tricky to tell which is the primary one, only works if one number covers all of those -> ask the user maybe?]

b) both numbers [the better option I would say]

**Comment by lduboeuf** [comment]
@Danfro as it seems not related to this app can we close that issue ?
Phone numbers displayed in address book app are retrieved from the Sim card. Sometimes for wathever reason the provider does not set it. As a work around, there is an app to overwrite phone number field ( see  https://github.com/ubports/ubuntu-touch/issues/1422 )

**Comment by Danfro** [comment]
Yes you are right.
