### ISSUE TITLE
Old Components

### ISSUE THREAD

**Issue by cibersheep** [ubports/address-book-app#112]
We still use ListItems in `src/imports/Settings/SettingsPage.qml` which is deprecated

**Comment by lduboeuf** [comment]
could you please point to the new Component or import ?

**Comment by cibersheep** [comment]
Sure, https://api-docs.ubports.com/sdk/apps/qml/Ubuntu.Components/ListItem.html

It's not a 1 on 1 replacement though

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/112
