### ISSUE TITLE
Unable to build from clickable

### ISSUE THREAD

**Issue by rubencarneiro** [ubports/address-book-app#118]
clickable
Sending build context to Docker daemon  3.584kB
Step 1/3 : FROM clickable/ubuntu-sdk:16.04-armhf
 ---> a6eb470aafc3
Step 2/3 : RUN echo set debconf/frontend Noninteractive | debconf-communicate && echo set debconf/priority critical | debconf-communicate
 ---> Using cache
 ---> f600430542a1
Step 3/3 : RUN apt-get update && apt-get install -y --force-yes --no-install-recommends libqofono-dev:armhf ofono-dev:armhf intltool:armhf pkg-config:armhf qt5-default:armhf qtbase5-dev:armhf qtdeclarative5-dev:armhf qtpim5-dev:armhf qml-module-ofono:armhf qtdeclarative5-buteo-syncfw0.1:armhf qtdeclarative5-gsettings1.0:armhf qtdeclarative5-ubuntu-history0.1:armhf qtdeclarative5-ubuntu-keyboard-extensions0.1:armhf qtdeclarative5-ubuntu-telephony-phonenumber0.1:armhf qtdeclarative5-qtcontacts-plugin:armhf qml-module-qtquick2:armhf qtdeclarative5-qtcontacts-plugin:armhf && apt-get clean
 ---> Using cache
 ---> 6a2591c019e7
Successfully built 6a2591c019e7
Successfully tagged clickable/ubuntu-sdk:16.04-armhf-c2cc1906-9466-4a8e-b06e-70b5c261fd48
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Autopilot tests disabled: autopilot binary not found
-- Found PkgConfig: arm-linux-gnueabihf-pkg-config  
-- Checking for module 'libqofono-dev'
--   /usr/bin/pkg-config: 1: /usr/bin/pkg-config: Syntax error: word unexpected (expecting ")")
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  CMakeLists.txt:25 (pkg_check_modules)
 
 
-- Configuring incomplete, errors occurred!
See also "/home/ruben/Transferências/address-book-app-master/build/arm-linux-gnueabihf/app/CMakeFiles/CMakeOutput.log".
Command exited with non-zero exit status 1, see above for details. This is most likely not a problem with Clickable.

**Comment by jwillikers** [comment]
I think I'm hitting a related error:
```console
No builder was specified, would you like to auto detect the builder [y/N]: y
Auto detected builder to be "cmake"
* daemon not running; starting now at tcp:5037
* daemon started successfully
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Autopilot tests disabled: autopilot binary not found
-- Found PkgConfig: arm-linux-gnueabihf-pkg-config (found version "0.29.1") 
-- Checking for module 'qofono-qt5'
--   No package 'qofono-qt5' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  CMakeLists.txt:25 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/jordan/git/com/github/ubports/address-book-app/build/arm-linux-gnueabihf/app/CMakeFiles/CMakeOutput.log".
Command exited with non-zero exit status 1, see above for details. This is most likely not a problem with Clickable.
```

It looks like PR #121 will fix this.
