### ISSUE TITLE
Sort contacts by the last name

### ISSUE THREAD

**Issue by zlamalp** [ubports/address-book-app#12]
It would be nice to have an config option in settings to sort contacts by "last name, first name", right now it's sorted by "first name" first. Like this it's hard to find a proper contact for people I do not call offer and do not remember their first name. Also it would help to keep each family together in a contact list.

**Comment by Flohack74** [comment]
I agree! :)

**Comment by lool-lauris** [comment]
I also support this request for sorting on the name. This is an essential feature.

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/12
