### ISSUE TITLE
Crossbuilder fails

### ISSUE THREAD

**Issue by jwillikers** [ubports/address-book-app#133]
When running `crossbuilder` in the project directory, it fails to build.

The console output when running `crossbuilder` is [here](https://paste.ubuntu.com/p/BQF2T3DYVy/).

I can fix the problem by attaching `:all` to the `dh-translations` package in the `debian/control` file, as follows.
```
Build-Depends: cmake,
               dbus,
               debhelper (>= 9),
               dh-apparmor,
               dh-translations:all,
               libgl1-mesa-dev | libgl-dev,
               libgles2-mesa-dev,
```

**Comment by lduboeuf** [comment]
could you please paste the log in a appropriate provider ? (e.g https://paste.ubuntu.com/ )
This is a common issue with crossbuilder. Just run `crossbuilder inst-foreign dh-translations`

**Comment by jwillikers** [comment]
@lduboeuf, yeah, no problem. I'll make sure to use one next time.
If this is a common issue, should this be mentioned in the [Making changes and testing locally](http://docs.ubports.com/en/latest/systemdev/testing-locally.html) section of the UBPorts docs?

**Comment by lduboeuf** [comment]
I would  add more an issue in the CLI repo here https://github.com/ubports/crossbuilder/issues
i'm not 100% sure though it is a crossbuilder issue or if every debian projects needs to be updated
And maybe by adding something in the readme here

**Comment by jwillikers** [comment]
Thanks @lduboeuf, I'll do just that 👍

**Comment by lduboeuf** [comment]
example for messaging app: https://github.com/ubports/messaging-app#building-with-crossbuilder

**Comment by jwillikers** [comment]
Looks like it is an issue in the dh-translations package itself: https://github.com/ubports/crossbuilder/issues/4

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/133
