### ISSUE TITLE
Shadow variable

### ISSUE THREAD

**Issue by maddin200** [ubports/address-book-app#138]
/src/app/addressbookapp.cpp line 324
variable 'args' shadows line 319
 QStringList args;
    QMap<QString, QStringList> methodsMetaData;
    if (methodsMetaData.isEmpty()) {
        QStringList args;

**Comment by cibersheep** [comment]
Could you provide some context?

**Comment by lduboeuf** [comment]
yes it seems that a variable is declared twice, will fix it
