### ISSUE TITLE
Return to the generic image for a contact

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/address-book-app#139]
It seems possible to choose a custom image for a contact, to change the custom image, but not to return to the generic image for a contact.

**Comment by cibersheep** [comment]
I can confirm this.

Possible solutions:
 - Tapping on the image, if not empty, give you the option to change or delete the current
 - add a button to delete the image (?)

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/139
