### ISSUE TITLE
display a message if no phone number found

### ISSUE THREAD

**Issue by lduboeuf** [ubports/address-book-app#142]

**Comment by UniversalSuperBox** [comment]
@lduboeuf could you please add some steps to this issue so QA testers are able to confirm it is fixed?

**Comment by lduboeuf** [comment]
humm, this is testable for whom have phoneNumbers not set on SIM Card ( provider has not set the phone number or not allows to ).

I've wrote with @Danfro an app to write the subscribers property for the SIM Card, but need to be tweaked in order to write an empty one: https://github.com/lduboeuf/simreader/blob/master/qml/Sim.qml#L129

Edit: Oh just tested with an old invalid SIM card, and we can see the message

**Comment by lduboeuf** [comment]
I admit, it is not a perfect solution:
![screenshot20210223_233220381](https://user-images.githubusercontent.com/11663835/108917246-bd83bd00-762f-11eb-848d-cc54a0870a37.png)

User might don't know what to do with this message

**Comment by lduboeuf** [comment]
humm, should we revert ?

**Comment by Danfro** [comment]
Not perfect, but it does give at least an indication what's wrong?

--

**Comment by UniversalSuperBox** [comment]
Seems fine to me. Is there anything the user could possibly do?

**Comment by lduboeuf** [comment]
use the SimReader app (not in the OpenStore) or via DBus callt to try to write the number to the SIM card... But will not work in every cases. @Danfro  can talk about that experience ;-)

**Comment by Danfro** [comment]
Here a link to [SimEditor](https://gitlab.com/Danfro/simeditor)'s repo in case someone wants to know how it works.
The app does allow to write your phone number to the sim card. BUT only if the provider allows that. Some do, some don't.

Ideally the app's functionality should be included into network settings I suppose - if technically possible.

**Comment by Danfro** [comment]
For testers:

Check if 
a) _contacts app -> settings_ displays your phone number(s)
b) _system settings -> network_  your phone number(s) is(are) displayed or your sim card number

If your phone number(s) is(are) displayed, you are lucky. Your provider stored your phone number on your sim card. :smile: 

If your phone number(s) does not appear, you should find the note as shown further up in this thread "Could not read phone number from sim card" in contacts app. System settings will show your sim card number.

**Comment by cibersheep** [comment]
-SIM number is shown on Arale (dev channel)
-Error message is shown on E5 (with no SIM) on both slots

**Comment by lgtrombetta** [comment]
I confirm the error message appears on the contacts app settings.

I'm on RC 2021-W08 on a Nexus 6P with a SIM card inserted.

**Comment by dadandalive** [comment]
I confirm: on Nexus 5, RC 2021-W10 the  error message is shown in Contacts settings.

**Comment by ghost** [comment]
I confirm: With BQ Aquaris E4.5 and RC 2021-W10, the info message is shown in Contacts settings.
(Feedback: At first, I thought that these mean that no numbers are stored on SIM Card whatsoever.
Maybe this wording is more concise: "The phone number associated with the SIM card was not found.")
