### ISSUE TITLE
Want to help but where to start

### ISSUE THREAD

**Issue by gewooneendeveloper** [ubports/address-book-app#143]
Hi, i like to help. 
is there anything that i can help with or can you tell me where to start?

**Comment by lduboeuf** [comment]
Hi and Welcome, have you looked at issues that you want to fix, implement ?

**Comment by cibersheep** [comment]
Additionally to lduboeuf comment, what are your skills?
- Developer skills? Adding sync features with nextCloud could be a cool thing to have
- Design skills? Could we add fields to use?
- Language skill? Want to check translation?
- Social skills? Want to talk about the operating system? Videoblogs? User interface examples? New user guide?

Tip:

There is some «help wanted» issues: https://github.com/ubports/address-book-app/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

**Comment by cybercrypt13** [comment]
So I would also like to help and would like to know where the best place to go in order to learn about the program. ie: language, layout...

There are seemingly many things that need to be added to get the program up to par with Android and iOS and interested in understanding what the process is.  I've been programming for 30 years but never on Open Source projects so need to figure out the process for getting involved.

Thanks,

Glenn

**Comment by lduboeuf** [comment]
@cybercrypt13 Have you checked https://docs.ubports.com/en/latest/appdev/index.html ?
My personal learning path was:
Qt and QML: e.g: https://qmlbook.github.io/
Ubuntu UI toolkit ( now called Lomiri UI toolkit ) : https://api-docs.ubports.com/
Tools: Clickable  (https://clickable-ut.dev/en/latest/) or Crossbuilder for building debian package on your device (https://docs.ubports.com/en/latest/systemdev/testing-locally.html#cross-building-with-crossbuilder)
IDE:  QtCreator with `clickable ide qtcreator` command. A short video about that: https://youtu.be/CCHL_tYDVL0

For a hello world app demo: https://youtu.be/TE-s5522v0Y

So, to get started with address-book-app, you should be able to build and run on your device with `clickable` or locally: `clickable desktop`

**Comment by lduboeuf** [comment]
@cybercrypt13 and i agree documentation should be enhanced for newcomers, maybe by you ?

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/143
