### ISSUE TITLE
Include REV and UID field in file export

### ISSUE THREAD

**Issue by padu22** [ubports/address-book-app#154]
I noticed that exporting contacts via UI leads to noticeably smaller files than exporting via

$ syncevolution --export /home/phablet/Documents/utcontacts.vcf backend=evolution-contacts

Further inspections shows that records from the shell command contain some more optional (REV, UID) plus some non-standard vcard fields.  While I don't care about the non-standard ones, I do wonder if dropping the former is intentional.

Granted, when importing contacts from a .vcf file, I think an application should not use existing information from fields REV and UID.  That is, it would better create unique UIDs itself and set last modification time to the time of the import.  Though, during export, I'd perhaps not drop those fields as the information may be of interest (for REV).  Or it could make life easier when doing some further processing of an exported .vcf file (for UID).  Think of two intentionally identical, e.g., sparsely filled, contacts that have different UID.  UT contacts app would show those as two distinct contacts.  But after UI export, that explicit information is lost.

I'm not saying the current behaviour is wrong.  After all REV and UID are optional fields only.  But I'm not convinced either, dropping is the best way to handle REV and UID fields during export.  My recommendation is to include both fields.

**Comment by padu22** [comment]
One more consideration: I have no idea how .vcf import works.  In case the address book currently uses existing UID fields from a .vcf file, it should not duplicate data fields when importing the same file twice.  Either ignore contacts with the same UID or generate a new UID for the second contact.  Doubled contacts can be tidied up one or the other way (editing .vcf export).  The situation that is to be avoided is double data within a single contact.

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/154
