### ISSUE TITLE
Exporting contact with apostrophe ' in name gets stuck on load popup

### ISSUE THREAD

**Issue by jezek** [ubports/address-book-app#157]
Mentioned in #119 

Reproduce:
- create contact with apostrophe (```'```) in name (eg. ```Connor O'Brian```)
- export contact to ```File Manager``` using share button

Expected: Contact exported
Result: Export gets stuck on load popup

**Comment by lduboeuf** [comment]
more over we should list all characters that needs to be escaped and replaced with _ or something else

**Comment by jezek** [comment]
For inspiration, this is how [node.js sanitizes filename](https://www.npmjs.com/package/sanitize-filename).
https://github.com/parshap/node-sanitize-filename/blob/master/index.js

Edit: and then can be tested with some strings from: https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.txt :wink:
