### ISSUE TITLE
Importing contacts from .vcf file creates an error and imports only the first contact/address.

### ISSUE THREAD

**Issue by kebabfish** [ubports/address-book-app#16]
Device: bq E4.5
OS: Switched from UT (canonical) to UT 15.04 r2 (ubports)
Error: Importing contacts file created an error

**Problem**:
Import contacts via "files" -> click on .vcf file -> open with "contacts" gives the error "Failed to import". As a results only the first contact is imported.

**Solution**:
Open the terminal and enter the following command: "syncevolution --import /path/to/file/allcontacts.vcf backend=evolution-contacts database=Personal"

Note: "Personal" may vary with different languages.

**Comment by lduboeuf** [comment]
@kebabfish is it still the case ?

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/16
