### ISSUE TITLE
FastScroll gets in the way of the Call action

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/address-book-app#162]
After scrolling, the FastScroll list remains on screen for a few seconds. During this time, pulling a contact to the left to expose its trailing actions reveals the call action. For most contacts (except those at the very beginning and end of the list), the call action is underneath the FastScroll list. Trying to tap on the call action instead activates the FastScroll.

![Screenshot of contacts-app showing A-Z fastscroll list overlaying the Call action](https://user-images.githubusercontent.com/21966173/93220935-c4c6a680-f732-11ea-8deb-0f34f02474db.png)

**Comment by farkasdvd** [comment]
Device: bq e5
Build: 2020-W43

LGTM
