### ISSUE TITLE
Searching contacts is problematic when there are a lot of contacts

### ISSUE THREAD

**Issue by Thanasis1101** [ubports/address-book-app#175]
I have a problem when searching through contacts and there are a lot of contacts. While typing the search term, the contacts list should be updated for every new character. Instead, this is happening sometimes and sometimes it isn't. The list doesn't delay to update, but **the list is never updated**. The same thing also takes place in the search of dialer-app and messaging-app.

This problem occurs on **Nexus 4 / Nexus 5** with **OTA-14 / OTA-15** while having **2700 contacts**.
I'd like to add that in older versions  of the operating system (**ubuntu touch 15.04**) the search worked fine.

**Comment by lduboeuf** [comment]
confirmed, even with 250 contacts BQ4.5

**Comment by lduboeuf** [comment]
so maybe we should wait for Contact backend change and see if it still occurs.   @mardy do you have any news with the contact backend migration ?
Did some quick testings, and confirmed that fetching contact is very slow ( about 300ms for 25 contacts). There is an issue when there is a pending request and we want to overwrite it by another query, backend continue to fetch data and don't care about the change whatever you do with filter.

**Comment by mardy** [comment]
> so maybe we should wait for Contact backend change and see if it still occurs. @mardy do you have any news with the contact backend migration ?

Most of the work has been done, but I got busy right when it was time to test it, and there was no one available to test it. There was a group of German users who setup a sprint to work on this, but for some reason it didn't happen. Now with the migration to Qt 5.12 everything needs to be rebuilt, possibly with some changes, and I'd be willing to do that only if there was someone who would help me with the testing and basically drive the feature to completion. I can do the coding, that's no problem, but there needs to be someone to give me priorities and ping me, otherwise I get distracted with million other things :-)

**Comment by lduboeuf** [comment]
@mardy i can join the party as i know a bit about contact API and core apps that use it.
i will pm you

**Comment by Flohack74** [comment]
Just my 2 cents, I think the change handler for the input field should wait a few more msecs before triggering the search. Typing is slower than on a keyboard on mobile devices, hence give the user more time to finish typing. Also, every character must restart the search timer again. I made a solution on TELEports that works very well if you are interested.
Also, typing while search is in progress needs to cancel the previous search, and start a new one. That can be cumbersome process to deal with the async functions, and the QtFuture or whatever you have in place there

**Comment by lduboeuf** [comment]
@Flohack74 thanks for the hint. 
But the thing is that ContactModel ( the component responsible for contact search ) has some missing parts. E.g we never know when search is fully retrieved or we can't explicitely cancel a request, changing the filter sometimes work sometimes not. So we would need to implement our custom search component in c++. That is what i've done for the DialPad contact search, and it behaves without surprise

**Comment by deucn** [comment]
Hello all, i'm migrating from BB Passport to MI A2 running Ubports Ubuntu Touch and was able to sync my 6037 contacts from BB Passport to Ubuntu TOuch using sync evolution. All contacts are in, but can't search for a contact. Can someone help?

**Comment by lduboeuf** [comment]
> Hello all, i'm migrating from BB Passport to MI A2 running Ubports Ubuntu Touch and was able to sync my 6037 contacts from BB Passport to Ubuntu TOuch using sync evolution. All contacts are in, but can't search for a contact. Can someone help?

there is issues for searching it seems. Have you tried to type slowly or use backspace at the end and re-enter the last letter ?

**Comment by deucn** [comment]
Dear Iduboeuf, thank you for the response.  

currently there are 6036 contacts in the phone (MI A2 - 6GB 128GB), no duplicates, the battery charge is 7%, no background applications. 

In this scenario, i'm searching for contacts with "delhi" in the said phone.

steps followed.

1) from default desktop screen, contacts app was selected.
2) on top right, there is the search button. tapped on it.
3) delhi was typed @ one character per second rate.
4) waited for 5 seconds, no developments observed.
5) on sixth second, i have deleted "i" from delhi and punched back "i".
6) the process of adding and deleting I was done for four or five times.
7) approx 12 seconds later 55 contacts were shown.

Notes:-
A) Average size of the contact is 160bytes as individual VCF files, total size was 1.2mb or so.

B) the contacts.db file in the phone is showing 8mb.

C) the contact is of VCF 3.0 format.

cheers.

happy new year.

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/175
