### ISSUE TITLE
XSS in Contacts app.

### ISSUE THREAD

**Issue by testingweb624** [ubports/address-book-app#176]
Hi,
I got a XSS in Contacts app which gets triggered after importing contacts.vcf file where in one of the Contact name has html XSS payload.

It triggered on Contacts when we open the app. So, Please look into this matter.

Regards,
DonReddy
![contacts](https://user-images.githubusercontent.com/29984285/103869058-ce17bc80-50ef-11eb-911e-14d48962e734.png)

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/176
