### ISSUE TITLE
Cover more fields in contact search

### ISSUE THREAD

**Issue by padu22** [ubports/address-book-app#178]
**Current behaviour:**

Searching contacts does not seem to cover vcard `ORG` field, that may contain information about an organization a person has a relation to (a company someone is employed at etc.)

**Expected behaviour:**

Include `ORG` field in address book search.

**Rationale:**

Searching the address book for people that you have less frequent contact with, but that are important persons to you nevertheless – say people that are employed at a certain company or an administrative office – one finds himself sometimes wondering what the exact name of a person was.  In that situation, typing in an organization name in the search field returning a list of people with a matching `ORG` entry would be helpful.

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/178
