### ISSUE TITLE
Create New Contact Focus

### ISSUE THREAD

**Issue by cybercrypt13** [ubports/address-book-app#185]
When opening new contact or when creating new contact from number in phone book, it should focus on first name field.  Currently you have to click in field before you get a keyboard to type anything.  It is an extra click for zero return since there are probably zero cases where you'd do something different other than maybe entering a business name instead of a first name.

**Comment by lduboeuf** [comment]
Yes, for phone app, i would even expect that clicking on the "contact +" show directly the contact form

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/185
