### ISSUE TITLE
Entering a phone number on new contact

### ISSUE THREAD

**Issue by cybercrypt13** [ubports/address-book-app#186]
You can not touch into the phone field to enter a phone number.  You must press the next button.  If I touch into the phone area it should popup keyboard and allow me to enter the number.

**Comment by lduboeuf** [comment]
humm, no issue on OTA-17,BQ4.5.
Which device ?

**Comment by cybercrypt13** [comment]
Yeah, seems like it is working now.  I just upgraded OS the other day and haven't tested since then.

Thanks,

Glenn
