### ISSUE TITLE
Notes field

### ISSUE THREAD

**Issue by cybercrypt13** [ubports/address-book-app#187]
When I create new contacts I usually add a note to remind me where I met the person or what they are related to.  I don't see any way to add a note field in the current version.  Is this possible?

Thanks,

Glenn

**Comment by lduboeuf** [comment]
I've tried somrhing once but without luck, see https://github.com/ubports/address-book-service/pull/16
But like for others things, better to wait for backend change

**Comment by cybercrypt13** [comment]
I don't even see where you can enter a note field.  Under add field section there is nothing there for "Note".

**Comment by lduboeuf** [comment]
Notes is not implemented yet

**Comment by cybercrypt13** [comment]
Is it not implemented because no one is working on project anymore or is there a technical reason.  I would seem a change like this would take very little effort to get done.  Not implying anything, just trying to understand how the project is progressing and if anyone is working on it.

Thanks,

Glenn

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/187
