### ISSUE TITLE
Issue Compiling

### ISSUE THREAD

**Issue by cybercrypt13** [ubports/address-book-app#190]
Is there somewhere that lists what packages are required to compile the program?  I'm getting errors like: Could not find a package configuration file provided by "Qt5Contacts" with
  any of the following names:

    Qt5ContactsConfig.cmake
    qt5contacts-config.cmake

Since I don't program in Linux I'm unsure of what to do to get past this.  I assume I'm missing a package somewhere but have been following your README file to compile.  I've already had to use apt-file search to install a number of other packages but the contactsconfig listed above doesn't yield results.  Also tried searching internet but so far nothing has yielded a solution.

Thanks,

Glenn

**Comment by lduboeuf** [comment]
I personally use `clickable` for compiling or `crossbuilder`, it should work

**Comment by lduboeuf** [comment]
moreover you can check required dependencies with the debian/control file

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/190
