### ISSUE TITLE
duplicate contacts handler + more account

### ISSUE THREAD

**Issue by HackerShohag** [ubports/address-book-app#199]
There's no support for handling duplicate contacts like merging the duplicates or keeping one instead of two. And also there's only support for google contacts not for any other accounts like outlook, or any others. This would be a lot helpful.

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/199
