### ISSUE TITLE
A contact should have more options/actions 

### ISSUE THREAD

**Issue by mymike00** [ubports/address-book-app#2]
When I'm on the info about a contact I have a button to message with the contact and another to call him. The second one doesn't call the contact however, it just copy the number in the Dialer.
It was great to add another button that call directly the contact (sometimes I tap to call someone and I wait for his reply but the call isn't stared yet ^^)

I was thinking something like this:
![contact](https://user-images.githubusercontent.com/28359593/26940450-fabfa9d2-4c7a-11e7-8d4b-5746b9f9d702.png)
maybe it requires a new suru icon (to copy the phone number in the Dialer, to call directly it's ok the handset), something that joins the handset and the copy-icon? or just an arrow with the handset? the icon of the external link? Well I don't know I'm not a designer, just some ideas...

![call-arrow svg](https://user-images.githubusercontent.com/28359593/26941090-7bedd428-4c7d-11e7-8c4c-4255dc1fd708.png)             ![call-arrow2 svg](https://user-images.githubusercontent.com/28359593/26941091-7beebac8-4c7d-11e7-8053-ad2c9cb0a1db.png)              ![call-copy svg](https://user-images.githubusercontent.com/28359593/26941093-7c042a8e-4c7d-11e7-955e-c924883f2149.png)               ![call-to svg](https://user-images.githubusercontent.com/28359593/26941092-7bff7dcc-4c7d-11e7-803f-f663a2a62c8e.png)

So 3 icons:
- [x] Message icon - to send a message
- [x] Handset icon - to call directly
- [ ] todo icon - to copy the number in the Dialer

This is my idea, but the 2nd and the 3rd icons can be swapped...

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/2
