### ISSUE TITLE
favorites sometimes not available

### ISSUE THREAD

**Issue by Danfro** [ubports/address-book-app#200]
Xperia X, devel

Sometimes when pressing the favorites tab, nothing happens. Sometimes it works. I could not yet pinpoint it when it will work and when not.

**Comment by Danfro** [comment]
If you do favs-all-favs-all... a couple of times, favs get displayed every third or second time.

**Comment by Danfro** [comment]
This behaviour was confirmed by Steven on Redmi Note 9 Pro, RC week 52.

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/200
