### ISSUE TITLE
Improvement of the user interface when adding a new field

### ISSUE THREAD

**Issue by Anne017** [ubports/address-book-app#22]
There is no field to add someone's physical address (street, country), there should be this option.
And also an icon to navigate to this person (for example with uNav).

**Comment by Danfro** [comment]
Shouldn't this (old) issue be closed?
We do have an option to store an address for contacts.
Although I can't remember a time when I couldn't do this ... ;-)

**Comment by hummlbach** [comment]
Yes you're perfectly right. Like the idea of having a button for navigation there. :) (but which navigation app would be used if there was more than one?)

**Comment by Anne017** [comment]
Oo
OMG this field already exists (maybe since the beginning) but I have absolutely not guessed you could scroll down to view additional fields...
Thank you for the tips @hummlbach!

Now I better understand @Danfro's comment.
So let's rephrase this issue, I am maybe not the only one tricked.
Would it be possible to improve the user interface, for example by expanding the full list of fields by default?
For the navigation button, I am opening a new issue since the topic seems a little bit different.

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/22
