### ISSUE TITLE
Accounts

### ISSUE THREAD

**Issue by ronnietucker** [ubports/address-book-app#23]
This relates to the 'Accounts' feature in System Settings. Wasn't sure where to put this. Sorry if it's in the wrong place.

If I go to accounts and choose Google. I get the spinning blue circle forever.

MX4 with 16.04/dev.

**Comment by lduboeuf** [comment]
Is it from the app settings or system settings ?. If it is the later, then the issue should me moved to https://github.com/ubports/ubuntu-touch/issues

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/23
