### ISSUE TITLE
Info Field for Contacts

### ISSUE THREAD

**Issue by BlueKenny** [ubports/address-book-app#31]
I have a lot of (small) informations that i need for my customers in my contact, these are saved on my Nextcloud server, but unfortunaly the "info" field doesn't exists in the app so there things aren't importet

Is it possible to add this field ?

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/31
