### ISSUE TITLE
Favorite button hard to see

### ISSUE THREAD

**Issue by bhdouglass** [ubports/address-book-app#33]
Depending on the background image for a contact the favorite/star button can be difficult to see. I suggest moving it to the header buttons, but that's just me.

**Comment by Flohack74** [comment]
There is a favorite button? Didnt know that xD

**Comment by bhdouglass** [comment]
Exactly! :joy:

**Comment by lduboeuf** [comment]
@bhdouglass,  fixed by b195f477abb622acf082390570911fa434a7fd73

**Comment by lduboeuf** [comment]
@Flohack74 or @bhdouglass ,  that one could be closed
