### ISSUE TITLE
Merge xenial branch from master

### ISSUE THREAD

**Issue by Flohack74** [ubports/address-book-app#37]
Our automatic build needs the xenial branch to be able to build nightly versions correctly into the rootfs image.

**Comment by lduboeuf** [comment]
@Flohack74 isn't now the case ?

**Comment by Flohack74** [comment]
Hmm do you see any issues at the moment with publishing new versions? If no we can close it...

**Comment by lduboeuf** [comment]
sorry can't tell you, though it was an old issue that was not closed

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/37
