### ISSUE TITLE
Only primary telephone numbers are exported

### ISSUE THREAD

**Issue by Flohack74** [ubports/address-book-app#4]
See also https://github.com/ubports/telegram-app/issues/50: When exporting contacts from the addressbook it is not possible to export any other phone number than the first one that has been entered.

**Comment by lduboeuf** [comment]
I can't reproduce it, the contact in vcf have all numbers set

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/4
