### ISSUE TITLE
Contacts Initial Layout

### ISSUE THREAD

**Issue by Dave1152000** [ubports/address-book-app#42]
Shouldn't the Contacts page start with the Favourites showing rather than All. Presumably the Favourites are what everyone uses most.

**Comment by Gabriele69** [comment]
"Presumably the Favourites are what everyone uses most."
Favourites should be all "starred" contacts

**Comment by cibersheep** [comment]
This maybe changed now:

- When opening Dialer you have latest contacts from BottomEdge
- Now, also favorites in the main Dialer page

If I open Contacts would be to search for a contact rather than a favorite

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/42
