### ISSUE TITLE
No birthday field 

### ISSUE THREAD

**Issue by PhoenixLandPirate** [ubports/address-book-app#5]
There's no field to add someone's birthday, there should be this option, and it should sync with the calendar to show someone's birthday is on a certain day.

**Comment by Anne017** [comment]
Good idea!
Maybe it could be a more general "Anniversary" field with several options below:
Birthday (by default), wedding, memorial, etc.
The same way you have the "Phone" field and the sub-categories Home, work, cell phone, etc.

**Comment by lduboeuf** [comment]
so i've made some progress with that, luckily the sync between address-book-app and calendar is already in place.
Quite hard to get into UI for field edition but i'm close.
Currently i am more stuck with a very weird thing when storing the birthdate, the calendar have the correct date set but the contact detail always have the saved date minus 1 day. (i've fought with locale, toString and so on without luck) I don't know if it is a bug in QtContact or in my code.

Here is some details: when i set birthday with `"birthday":"1990-04-10T12:00:00.000Z"` , after saveContact function, the returned value is `"birthday":"1990-04-09T20:00:00.000Z"`
(i'm in GMT +2 zone )
in database the BDAY is well stored: `BDAY:1990-04-10`

**Comment by lduboeuf** [comment]
So, the feature is ready to test, note that two known bugs and waiting to be merged:

- Displayed date in contact might be different than the set one ( but the right date is stored )
- Pointing to calendar to the correct date does not work

Some focus annoyance also are expected when adding a birthday

Check out the app here: https://drive.google.com/file/d/1JVPkuDY10Qh7fEYkUAIskuR2c9K7b2ah/view?usp=sharing
( note that it will not delete the current address-book-app, but will create another one with the same icon. Beware that the app share the same data as the original one )
Backup is always a good option:
`adb pull /home/phablet/.local/share/evolution/addressbook/system/contacts.db`
