### ISSUE TITLE
xvfb should be marked with <!nocheck>

### ISSUE THREAD

**Issue by padraic7a** [ubports/address-book-app#50]
## Description:

Crossbuilder fails to build the app due to a problem with unmet dependencies. 

## Device:

Ubuntu 18.04 on the desktop. BQ M10 16.04

## Steps to reproduce:

Run crossbuilder to attempt to build the app as per instructions here: https://docs.ubports.com/en/latest/appdev/system-software.html#cross-building-with-crossbuilder

## Expected behaviour:

"Crossbuilder will do everything for you: it will create the LXD container, download the development image, install all your package build dependencies, perform the build .... "

## Actual behaviour:

Crossbuilder sets up the LXD container, downloads the development image and fails on installing dependencies.

## Logs and additional information:

Attempting to build with crossbuilder returns this error: 

```
builddeps:address-book-app:armhf : Depends: dh-translations:armhf but it is not installable
                                    Depends: xvfb:armhf
```

## Discussion 

From discussion with @mardy on [this](https://github.com/ubports/crossbuilder/issues/4) issue it seems that the issue is that ```xvfb``` should be marked with ```<!nocheck>``` in  ```debian/control.in``` and / or ```debian/control```.

**Comment by mardy** [comment]
Actually, the bug about dh-translations is not in address-book-app, but in dh-translations itself, so there isn't much we can do about it here.
He can, however, fix the `xvfb` part, by adding a `<!nocheck>` marker next to it (since it's only used for running tests).

**Comment by padraic7a** [comment]
Ah, my mistake. I have amended the issue now to reflect what @mardy said.

**Comment by lduboeuf** [comment]
After installing dh-translation, crossbuilder seems to build fine currently. Can we close that issue ?

**Comment by Flohack74** [comment]
I have no idea. @padraic7a still an issue?

**Comment by padraic7a** [comment]
I haven't tried it in a long time I'm afraid, and it will probably be some time before I do so again. If it works for others maybe it makes sense to close it.

**Comment by Flohack74** [comment]
Ok closing now
