### ISSUE TITLE
Groups for contacts

### ISSUE THREAD

**Issue by PhoenixLandPirate** [ubports/address-book-app#6]
To make it easier to find certain contacts you should be able to group them.
These would be shown in a different tab to select the groups.

**Comment by Flohack74** [comment]
Could it be just that you can add custom tags/labels to it? This can be done quick I think, could also use colors etc.

**Comment by ChloeWolfieGirl** [comment]
How would this work?
You can already favourite users, but that's all at the moment, but I was thinking, it'd be like favourting, but instead you replace favourite with family, or friends, or work, etc.

Depending on how tags work that might be good!

**Comment by Flohack74** [comment]
The benefit of tags in general is that you can assign more than one. Group always sounds like exclusive in or out ;)

**Comment by Thieb67k** [comment]
Hello,
I was looking for those groups possibilities as well. 
Moreover, that would be really time-saver to implement the multiple contact selection in the aim to create at once one group with pre-existing contacts.
Best.

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/6
