### ISSUE TITLE
Feature request: sorting contacts

### ISSUE THREAD

**Issue by idekovets** [ubports/address-book-app#61]
By default contacts sorts: First name, Middle name, Last name.

Need function to change it.

I will see: Last name, First name, Middle name.

`Contacts sort:
- First name, Last name
- Last name, First name`

**Comment by Danfro** [comment]
quite close a duplicate of #12

**Comment by hummlbach** [comment]
@Danfro thanks for pointing that out. Closing it as duplicate.
