### ISSUE TITLE
unable to share contacts via file manager

### ISSUE THREAD

**Issue by Danfro** [ubports/address-book-app#69]
I am unable to share contacts via file manager.
Using E5, 16.04 RC 2018-W01 (from 208-12-31).
(I do have the memory of this issue (sharing with file manager) has been talked about somewhere but I can not find it at the moment.)

**Steps to reproduce:**
open address-book app
tap and hold contact
select share icon
select file manager
select folder within file manager
press select

**expected result:**
a .vcf file with the contact(s) is created

**actual result:**
nothing happens

**Comment by james-lyon** [comment]
Same for me on krillin stable (OTA-7). Is there any other way of exporting contacts?

**Comment by Danfro** [comment]
With the latest update of file manager (0.6.1 from tuesday 2019-01-15) this problem is solved. @james-lyon can you please test this and confirm?

**Comment by james-lyon** [comment]
Yes I confirm the issue is now fixed for me also.

**Comment by Danfro** [comment]
Thanks to everyone who helped improving file manager!
