### ISSUE TITLE
No way to block contacts

### ISSUE THREAD

**Issue by PhoenixLandPirate** [ubports/address-book-app#7]
You should be able to block numbers so they can't call and/or text you.
(related to Messaging-app and dialer-app)

**Comment by Flohack74** [comment]
See also https://github.com/ubports/dialer-app/issues/18

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/7
