### ISSUE TITLE
Feature request - Add buttons on the right of someone's physical address

### ISSUE THREAD

**Issue by Anne017** [ubports/address-book-app#71]
Buttons/icons exist on the right of the main page of each contact to quickly call, text or send an email.
When the physical address (street, city) is filled in, it could be great to have similar buttons to visualize on a map and even navigate to this position.

See the initial discussion in issue #22.

**Comment by Anne017** [comment]
Example of icon in [Suru](http://icons.mivoligo.com/) to visualize the position on a map:

![location](https://user-images.githubusercontent.com/17686836/51090097-0db4a380-1777-11e9-9c13-f367bfffa3cd.png)

**Comment by Anne017** [comment]
Example of icons in [Suru](http://icons.mivoligo.com/) to navigate to the position:

![world](https://user-images.githubusercontent.com/17686836/51090121-70a63a80-1777-11e9-8112-a0fc376637bb.png)

![auto](https://user-images.githubusercontent.com/17686836/51090122-726ffe00-1777-11e9-8178-58f724153340.png)

Note: this second icon is for me more understandable form a design point of view, but it maintains the stereotype to use only a car to move, not a bike for instance.

**Comment by Anne017** [comment]
Example of icons in [Suru](http://icons.mivoligo.com/) to copy the text (and use it in a WebApp):

![copy](https://user-images.githubusercontent.com/17686836/51090202-88ca8980-1778-11e9-9dcc-ccdad97ad237.png)

**Comment by Anne017** [comment]
An interaction with uNav could be great.
If multiple maps/GPS applications are installed, perhaps the [Content Hub](http://docs.ubports.com/en/latest/appdev/guides/contenthub.html) could be used?

**Comment by cibersheep** [comment]
> An interaction with uNav could be great.
> If multiple maps/GPS applications are installed, perhaps the [Content Hub](http://docs.ubports.com/en/latest/appdev/guides/contenthub.html) could be used?

uNav was updated to receive more gps url, this would «work now» if implemented here. If more than one app captures gps URI (ie geo:// etc) the Content Hub should show letting you choose... if not, is a bug :)

**Comment by cibersheep** [comment]
> When the physical address (street, city) is filled in, it could be great to have similar buttons to visualize on a map and even navigate to this position.

This is interesting but (at leat uNav) doesn't receive a «text» to search. It can receive a [gps link](https://map.unav.me/?29.40038,2.3741609)

So maybe instead of adding this feature in the address, a field for gps position would be better?

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/71
