### ISSUE TITLE
Supporting any buteo-sync account causes tests to fail

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/address-book-app#73]
It seems like commit 6077d892cdef28568beddfbb594a0586254a2e00 did not update the tests for address-book-app to handle the changes to the ContactListView. The tests must be updated before the app can be built.

A log of the error can be found here: https://ci.ubports.com/blue/organizations/jenkins/address-book-app/detail/xenial_-_aba-control/1/pipeline#step-33-log-782

This was surfaced after fixing #72, but still blocks the merge of the fix.

**Comment by mardy** [comment]
Fixed!
