### ISSUE TITLE
pressing the search icon in address-book-app does not raise the OSK

### ISSUE THREAD

**Issue by Danfro** [ubports/address-book-app#79]
* Device: BQ E5 (vegetahd)

    * Channel: rc

    * Build: 2018-W41/2 all the way through to now 2019-W09

### Steps to reproduce

    * open contact app

    * tap on spyglass icon for search

    * not the search field opens

### Expected behavior

    * the keyboard should open as well, the search field should get the focus

### Actual behavior

    * no keyboard appears (although there is a bit of a flicker at the bottom, I suppose the app tries to raise the keyboard but it does not work)

    * swiping from the bottom brings up the "new contact" screen

    * I have to tap the search bar to get the keyboard

I think this is since the W41 update, maybe even the upgrade to 16.04
On 15.04 it was working fine.

Confirmed by @jezek  in his comment to #56 .

**Comment by ziggutas** [comment]
Nexus 7 (flo) rc 2019-W09, same problem in contacts app, have to tap the search bar to get the cursor and osk.

**Comment by mattbel10** [comment]
I can confirm this issue. Just adding that when you tap on the spyglass icon, if you pay attention at the same time to the search bar, you could spot the cursor showing up and suddenly disappearing without any OSK showing up.

Device: Meizu Pro5
Build: Ubuntu 16.04 (2019-W09)

**Comment by ziggutas** [comment]
BQ E4.5 2019-W09 
I can confirm exactly the same behaviour in the contacts app as described in the previous comment.

**Comment by Thieb67k** [comment]
I confirm that with mako device, on OTA-9.
That would be a small time-saving trick to get the OSK automatically opened.

**Comment by Danfro** [comment]
Actually I think the OSK does try to rise. But it just can't manage.
Can anyone else confirm, that when you press the search button/spyglass that at the bottom there is something flickering/moving?

**Comment by Thieb67k** [comment]
Well seen! I have not seen that detail before.
That is pretty discreet but I confirm that (nexus4, mako, OTA-9).
