### ISSUE TITLE
Expose vcf import in interface

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/address-book-app#8]
A report at [this forum thread[(https://forums.ubports.com/topic/420/successful-ubports-installation-and-contacts-import-on-nexus-5/2) states that .vcf files cannot be imported from within the Contacts app, but opening them from the file manager is possible.

Provide an option in the interface to browse for and import vcard files at will.

**Comment by Danfro** [comment]
As discussed in this issue [#1105](https://github.com/ubports/ubuntu-touch/issues/1105#issuecomment-487056279) and as suggested above an option to import .vcf files via content hub should be implemented.

**Comment by magdesign** [comment]
For people searching a way to import their .vcf contacts already placed somewhere on the phone (with usb transfer or download):

1. Open the filemanager
2. Select the contacs.vcf file
3. Select open with App
4. Select Contacts app and wait until they are imported

**Comment by lduboeuf** [comment]
ok, got a working thing here, will PR soon.
