### ISSUE TITLE
[devel] app crash at startup

### ISSUE THREAD

**Issue by lduboeuf** [ubports/address-book-app#83]
( version 20190506 ) , app is crashing at startup ( Nexus 5)  Anyone can confirm ?

**Comment by lduboeuf** [comment]
as a work around, i can open it with the dialer

**Comment by wagafo** [comment]
Which version of UT? I'm in OTA-9 Nexus 5 stable and I cannot confirm.

**Comment by lduboeuf** [comment]
on devel channel

it seems there are no relevant logs:
unity8 logs: https://paste.ubuntu.com/p/wxhwK64Ft9/
application logs: https://paste.ubuntu.com/p/Yk9N85pKPr/

**Comment by lduboeuf** [comment]
humm , by removing cache files, it is fine now `rm -rf .cache/com.ubuntu.address-book/AddressBookApp/qmlcache` 
I close that issue for now, but wondering why cache folder is not cleaned at restart
