### ISSUE TITLE
Exporting ubuntu_contacts.vcf in Files does not overwrite.

### ISSUE THREAD

**Issue by Thieb67k** [ubports/address-book-app#97]
Hello,

When exporting contacts in a folder that already possess an ubuntu_contacts.vcf file, that does not seems to overwrite.
The date remains the old one. (I did not dare to import it to avoid a mess like duplication..)
Plus, I cannot open that vcf file with "visionneur de documents" (Doc visualizer?). Does an App exist to do that (without importing)?

Thanks
(mako; stable channel; OTA5-->OTA-10)

**Comment by lduboeuf** [comment]
i think it is more an issue in Doc Viewer which should either replace or increment file name

**Comment by lduboeuf** [comment]
Well what can be done to avoid every app to handle file increment is to append the date at the end of the file.
